### ISSUE TITLE
Test on Mac

### ISSUE THREAD

**Issue by thekid** [xp-runners/reference#30]
Current idea:
- [x] Create xp-runners/spec - _see https://github.com/xp-runners/spec_
- [x] Use https://docs.travis-ci.com/user/multi-os/ <- @mikey179 I didn't know this existed! :cool: 
- [x] Use https-verified install from #29
- [x] Run xp -v
- [x] ~~Run further integration tests with a especially crafted class-main.php~~ -> will be done in following PRs

**Comment by thekid** [comment]
http://kwangyulseo.com/2015/04/06/building-mono-project-on-the-travis-ci-os-x-build-environment/

``` yaml
install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - ./build.sh Build
```
